require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AdvisesController do

  # This should return the minimal set of attributes required to create a valid
  # Advise. As you add validations to Advise, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString", "message" => "MyText", "order" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AdvisesController. Be sure to keep this updated too.
  let(:valid_session) { {} }


  describe "GET new" do
    it "assigns a new advise as @advise" do
      get :new, {}, valid_session
      assigns(:advise).should be_a_new(Advise)
    end
  end

  describe "GET edit" do
    it "assigns the requested advise as @advise" do
      advise = Advise.create! valid_attributes
      get :edit, {:id => advise.to_param}, valid_session
      assigns(:advise).should eq(advise)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      before :each do
        @advise = Advise.create! valid_attributes
        Advise.should_receive(:new).and_return(@advise)
        Advise.should_receive(:any?).and_return(false)
        post :create, {:advise => valid_attributes}, valid_session
      end
      it "creates a new Advise" do
        assigns(:advise).should eq(@advise)
      end

      it "assigns a newly created advise as @advise" do
        assigns(:advise).should be_a(Advise)
        assigns(:advise).should be_persisted
      end

      it "redirects to the created advise" do
        response.should redirect_to(root_url)
      end
    end

    describe "with invalid params" do
      before :each do
        @advise = Advise.create! valid_attributes
        Advise.should_receive(:new).and_return(@advise)
        Advise.should_receive(:any?).and_return(false)
        # Trigger the behavior that occurs when invalid params are submitted
        Advise.any_instance.stub(:save).and_return(false)
        post :create, {:advise => { "title" => "invalid value" }}, valid_session
      end
      it "assigns a newly created but unsaved advise as @advise" do
        assigns(:advise).should eq(@advise)
      end

      it "re-renders the 'new' template" do
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested advise" do
        advise = Advise.create! valid_attributes
        # Assuming there are no other advises in the database, this
        # specifies that the Advise created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Advise.any_instance.should_receive(:update).with({ "title" => "MyString" })
        put :update, {:id => advise.to_param, :advise => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested advise as @advise" do
        advise = Advise.create! valid_attributes
        put :update, {:id => advise.to_param, :advise => valid_attributes}, valid_session
        assigns(:advise).should eq(advise)
      end

      it "redirects to the advise" do
        advise = Advise.create! valid_attributes
        put :update, {:id => advise.to_param, :advise => valid_attributes}, valid_session
        response.should redirect_to(root_url)
      end
    end

    describe "with invalid params" do
      it "assigns the advise as @advise" do
        advise = Advise.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Advise.any_instance.stub(:save).and_return(false)
        put :update, {:id => advise.to_param, :advise => { "title" => "invalid value" }}, valid_session
        assigns(:advise).should eq(advise)
      end

      it "re-renders the 'edit' template" do
        advise = Advise.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Advise.any_instance.stub(:save).and_return(false)
        put :update, {:id => advise.to_param, :advise => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested advise" do
      advise = Advise.create! valid_attributes
      expect {
        delete :destroy, {:id => advise.to_param}, valid_session
      }.to change(Advise, :count).by(-1)
    end

    it "redirects to the advises list" do
      advise = Advise.create! valid_attributes
      delete :destroy, {:id => advise.to_param}, valid_session
      response.should redirect_to(root_url)
    end
  end

end
