require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AssistantEvaluationsController do

  # This should return the minimal set of attributes required to create a valid
  # AssistantEvaluation. As you add validations to AssistantEvaluation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "index_for_student" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AssistantEvaluationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all assistant_evaluations as @assistant_evaluations" do
      assistant_evaluation = AssistantEvaluation.create! valid_attributes
      get :index, {}, valid_session
      assigns(:assistant_evaluations).should eq([assistant_evaluation])
    end
  end

  describe "GET show" do
    it "assigns the requested assistant_evaluation as @assistant_evaluation" do
      assistant_evaluation = AssistantEvaluation.create! valid_attributes
      get :show, {:id => assistant_evaluation.to_param}, valid_session
      assigns(:assistant_evaluation).should eq(assistant_evaluation)
    end
  end

  describe "GET new" do
    it "assigns a new assistant_evaluation as @assistant_evaluation" do
      get :new, {}, valid_session
      assigns(:assistant_evaluation).should be_a_new(AssistantEvaluation)
    end
  end

  describe "GET edit" do
    it "assigns the requested assistant_evaluation as @assistant_evaluation" do
      assistant_evaluation = AssistantEvaluation.create! valid_attributes
      get :edit, {:id => assistant_evaluation.to_param}, valid_session
      assigns(:assistant_evaluation).should eq(assistant_evaluation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AssistantEvaluation" do
        expect {
          post :create, {:assistant_evaluation => valid_attributes}, valid_session
        }.to change(AssistantEvaluation, :count).by(1)
      end

      it "assigns a newly created assistant_evaluation as @assistant_evaluation" do
        post :create, {:assistant_evaluation => valid_attributes}, valid_session
        assigns(:assistant_evaluation).should be_a(AssistantEvaluation)
        assigns(:assistant_evaluation).should be_persisted
      end

      it "redirects to the created assistant_evaluation" do
        post :create, {:assistant_evaluation => valid_attributes}, valid_session
        response.should redirect_to(AssistantEvaluation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved assistant_evaluation as @assistant_evaluation" do
        # Trigger the behavior that occurs when invalid params are submitted
        AssistantEvaluation.any_instance.stub(:save).and_return(false)
        post :create, {:assistant_evaluation => { "index_for_student" => "invalid value" }}, valid_session
        assigns(:assistant_evaluation).should be_a_new(AssistantEvaluation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AssistantEvaluation.any_instance.stub(:save).and_return(false)
        post :create, {:assistant_evaluation => { "index_for_student" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested assistant_evaluation" do
        assistant_evaluation = AssistantEvaluation.create! valid_attributes
        # Assuming there are no other assistant_evaluations in the database, this
        # specifies that the AssistantEvaluation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AssistantEvaluation.any_instance.should_receive(:update).with({ "index_for_student" => "MyString" })
        put :update, {:id => assistant_evaluation.to_param, :assistant_evaluation => { "index_for_student" => "MyString" }}, valid_session
      end

      it "assigns the requested assistant_evaluation as @assistant_evaluation" do
        assistant_evaluation = AssistantEvaluation.create! valid_attributes
        put :update, {:id => assistant_evaluation.to_param, :assistant_evaluation => valid_attributes}, valid_session
        assigns(:assistant_evaluation).should eq(assistant_evaluation)
      end

      it "redirects to the assistant_evaluation" do
        assistant_evaluation = AssistantEvaluation.create! valid_attributes
        put :update, {:id => assistant_evaluation.to_param, :assistant_evaluation => valid_attributes}, valid_session
        response.should redirect_to(assistant_evaluation)
      end
    end

    describe "with invalid params" do
      it "assigns the assistant_evaluation as @assistant_evaluation" do
        assistant_evaluation = AssistantEvaluation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AssistantEvaluation.any_instance.stub(:save).and_return(false)
        put :update, {:id => assistant_evaluation.to_param, :assistant_evaluation => { "index_for_student" => "invalid value" }}, valid_session
        assigns(:assistant_evaluation).should eq(assistant_evaluation)
      end

      it "re-renders the 'edit' template" do
        assistant_evaluation = AssistantEvaluation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AssistantEvaluation.any_instance.stub(:save).and_return(false)
        put :update, {:id => assistant_evaluation.to_param, :assistant_evaluation => { "index_for_student" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested assistant_evaluation" do
      assistant_evaluation = AssistantEvaluation.create! valid_attributes
      expect {
        delete :destroy, {:id => assistant_evaluation.to_param}, valid_session
      }.to change(AssistantEvaluation, :count).by(-1)
    end

    it "redirects to the assistant_evaluations list" do
      assistant_evaluation = AssistantEvaluation.create! valid_attributes
      delete :destroy, {:id => assistant_evaluation.to_param}, valid_session
      response.should redirect_to(assistant_evaluations_url)
    end
  end

end
